blank_issues_enabled: false
contact_links:
  - name: Questions & discussion
    url: https://github.com/AlekseyBlokhin/lovelace-petkit-card/discussions
    about: For usage questions or general discussion, please use Discussions instead of an issue.
